### ISSUE TITLE
[BUG] no ntfy notifications

### ISSUE THREAD

**Issue by schklom** [mollyim/mollysocket#46]
Recently, I noticed I was not getting any notifications from the socket, despite Molly-UP reporting no issues.

I tried
```bash
$ sudo docker exec -it mollysocket bash
root@966ec8bd0e42:/data# mollysocket connection ping XXXX
[2024-08-28T15:50:45Z INFO  mollysocket::config] No config file supplied
thread 'main' panicked at src/cli/connection.rs:128:28:
called `Result::unwrap()` on an `Err` value: HTTP status server error (507 Insufficient Storage) for url (https://ntfy.sh/upXXXX?up=1)

Location:
    src/utils.rs:15:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It was working well until some time last week. Is this a problem from this service or ntfy? I can post an issue there.

If it helps, here is the same command with `RUSTBACKTRACE=full`
```sh
root@966ec8bd0e42:/data# RUST_BACKTRACE=full mollysocket connection ping XXXX
[2024-08-28T16:00:43Z INFO  mollysocket::config] No config file supplied
thread 'main' panicked at src/cli/connection.rs:128:28:
called `Result::unwrap()` on an `Err` value: HTTP status server error (507 Insufficient Storage) for url (https://ntfy.sh/upXXXX?up=1)

Location:
    src/utils.rs:15:5
stack backtrace:
   0:     0xaaaac0bd479c - <unknown>
   1:     0xaaaac0a2ac74 - <unknown>
   2:     0xaaaac0bb6344 - <unknown>
   3:     0xaaaac0bd8240 - <unknown>
   4:     0xaaaac0bd7bd8 - <unknown>
   5:     0xaaaac0bd8c14 - <unknown>
   6:     0xaaaac0bd8560 - <unknown>
   7:     0xaaaac0bd84cc - <unknown>
   8:     0xaaaac0bd84c0 - <unknown>
   9:     0xaaaac0939d38 - <unknown>
  10:     0xaaaac093a090 - <unknown>
  11:     0xaaaac09b8d4c - <unknown>
  12:     0xaaaac09e3ff4 - <unknown>
  13:     0xaaaac0975be0 - <unknown>
  14:     0xaaaac09e6150 - <unknown>
  15:     0xffffa23b7780 - <unknown>
  16:     0xffffa23b7858 - __libc_start_main
  17:     0xaaaac094e7f0 - <unknown>
  18:                0x0 - <unknown>
```

**Comment by p1gp1g** [comment]
https://docs.ntfy.sh/config/#subscriber-based-rate-limiting

It looks like you are trying to use an endpoint your ntfy client hasn't registered to yet

**Comment by schklom** [comment]
Apparently, I had updated the ntfy notification link on my phone without re-registering on Mollysocket 😢 My bad

**Comment by p1gp1g** [comment]
NP, glad you find out
